
# Let's Configure Delightful
[Knives]
	adamantium_knife = false
	allthemodium_knife = false
	amethyst_knife = false
	black_opal_knife = false
	bone_knife = false
	brass_knife = true
	bronze_knife = false
	constantan_knife = false
	copper_knife = false
	deorum_knife = false
	draco_arcanus_knife = false
	electrum_knife = false
	emerald_knife = false
	enderite_knife = false
	experience_knife = true
	fiery_knife = true
	gilded_quartz_knife = true
	invar_knife = false
	ironwood_knife = true
	kiwano_knife = false
	knightmetal_knife = true
	lapis_lazuli_knife = false
	large_amethyst_knife = false
	lead_knife = false
	leaf_knife = false
	living_knife = true
	mythril_knife = false
	netherite_opal_knife = false
	nickel_knife = false
	obsidian_infused_enderite_knife = false
	onyx_knife = false
	osmium_knife = false
	pendorite_knife = false
	refined_glowstone_knife = false
	refined_obsidian_knife = false
	reinforced_deorum_knife = false
	silver_knife = false
	sinisite_knife = false
	steel_knife = false
	steeleaf_knife = true
	thyrium_knife = false
	tin_knife = false
	warden_knife = false
	zinc_knife = true

[Cabinets]
	basalt_cabinet = true
	quartz_cabinet = true

["Foods and Other Items"]
	acorn = false
	acorn_sack = false
	animal_fat = false
	animal_oil_bottle = false
	azalea_tea = true
	berry_matcha_latte = true
	blueberry_pie_slice = true
	cactus_flesh = true
	cactus_steak = true
	cantaloupe = true
	cantaloupe_slice = true
	cheeseburger = true
	chopped_clover = true
	chunk_nugget = true
	chunkwich = true
	cooked_goat = true
	cooked_marshmallow_stick = true
	cooked_venison_chops = true
	crab_rangoon = true
	crimson_berry_pie_slice = true
	deluxe_cheeseburger = true
	ender_nectar = true
	field_salad = true
	glow_jelly_bottle = true
	green_apple_pie_slice = true
	green_tea_leaf = false
	honey_glazed_walnut = true
	jelly_bottle = true
	lavender_tea = true
	marshmallow_stick = true
	matcha = true
	matcha_ice_cream = true
	matcha_latte = true
	mini_melon = true
	nightshade_berry_pie_slice = true
	nut_butter_and_jelly_sandwich = true
	nut_butter_bottle = true
	prickly_pear_juice = true
	pumpkin_pie_slice = true
	raw_goat = false
	rock_candy = false
	salmonberries = true
	salmonberry_ice_cream = true
	salmonberry_pie = true
	salmonberry_pie_slice = true
	salmonberry_pips = true
	salmonberry_sack = true
	smore = true
	source_berry_pie_slice = true
	venison_chops = true
	#Allow cooking milk from nuts
	nut_milk = true
	#Allow cooking honey from honey and clovers
	clover_honey = false
	#Give items that are sliced off of blocks directly to player's inventory instead of dropping
	give_sliced_directly = false
	#Allow sliced melons to be juiced in-world (right click)
	melon_juicing = true
	#Make pumpkin pies a block with slices rather than an item eaten whole
	pumpkin_pie_overhaul = true
	coconut_curry = true
	sinigang = true

[Generation]
	#Chance of generating clusters. Smaller value = more frequent (once every ...). To disable, set the item Salmonberries to false above.
	#Range: > 0
	chance_wild_salmonberries = 30
	#Chance of generating clusters. Smaller value = more frequent (once every ...). To disable, set the item Mini Melon to false above.
	#Range: > 0
	chance_mini_melon = 30
	#Chance of generating clusters. Smaller value = more frequent (once every ...). To disable, set the item Cantaloupe to false above.
	#Range: > 0
	chance_cantaloupe = 50

