
#Here are configs that need reloading to take effect
[general]
	#Enable Creative Tab
	creative_tab = false
	#Enables custom Configured config screen
	custom_configured_screen = true

[features]
	corn = true
	grim_apple = true
	paper_bag = true
	popcorn = true
	carved_pumpkin = true
	splattered_egg = true
	candy_corn = true

