
[snowy_season]

	[snowy_season.snow_season_start]
		#Day from which villagers will start placing wreaths, presents and throwing snowballs
		#Range: 1 ~ 12
		month = 12
		#Day from which villagers will  start placing wreaths, presents and throwing snowballs
		#Range: 1 ~ 31
		day = 20

	[snowy_season.snow_season_end]
		#Day from which villagers will start removing placed wreaths
		#Range: 1 ~ 12
		month = 1
		#Day from which villagers will start removing placed wreaths
		#Range: 1 ~ 31
		day = 30

	[snowy_season.season_mod_compat]
		#Enables compatibility with Serene Seasons (Forge) or Fabric Seasons (Fabric). Only takes effect if the mod is installed. Will make snowy season only active during certain seasons. Note that this will override previous time window settings
		enabled = true
		#Season in which the mod villager AI behaviors will be active
		winter_season_sub_seasons = ["MID_WINTER", "LATE_WINTER"]

[misc]
	#Allows generated assets to depend on installed resource and data packs. This means that if for example you have a texture pack that changes the planks texture all generated sleds textures will be based off that one insteadDisable to have it only use vanilla assets
	pack_dependant_assets = true
	#Save generated resources to disk in a 'debug' folder in your game directory. Mainly for debug purposes but can be used to generate assets in all wood types for your mods :0
	debug_save_dynamic_pack = false
	#Enables custom Configured config screen
	custom_configured_screen = true
	mod_creative_tab = false

[blocks_and_items]
	sleds = true
	gumdrops = true
	glow_lights = true
	candy_cane = true
	ginger = true
	eggnog = true
	wreath = true
	snow_globe = true

